port = 'PORT'
proxy = 'IS_PROXIED'
num_workers = 'NUM_WORKERS'
log_level = 'LOG_LEVEL'
log_output = 'LOG_OUTPUT'
work_dir = 'WORK_DIR'
github_secret = 'GITHUB_SECRET'
gogs_secret = 'GOGS_SECRET'
[slack]
url = 'SLACK_URL'
channel = 'SLACK_CHANNEL'
[ssh]
pubkey = 'SSH_PUBKEY'
privkey = 'SSH_PRIVKEY'
password = 'SSH_PASSWORD'
[auth]
__name = 'DOCKER_AUTH'
__format = 'json'
